modified BottomSheetDrawer 3/5
flutterturkey/turkish-dictionary pull request #11
Opened 2020-03-20 00:09 UTC by mukireus

Done : iletisim
pub.dev/packages/url_launcher When click to phone number Make a phone call
Bug : iletisim page selected category animation

2020-03-20 06:17 UTC, mirkancal commented
LGTM

2020-03-20 07:31 UTC, onatcipli requested changes
Daha güzel ve daha kaliteli kod yazalım diye bu review'ı yapıyorum, Birden fazla kişi çalışırken kodun okunabilirliği arttırmak ve karışıklılığını düşürmek bize baya zaman kazandırabilir. Altta bir kaç yorum yaptım hepsinin yapılması şart değil hep beraber yavaş yavaşta düzeltebiliriz.
>bu arada bi ara komple projeye bi refactor atabiliriz bence

2020-03-20 07:31 UTC, onatcipli commented on sozluk/lib/page/home/home_page.dart
> +  Widget _itemTopMenu(String heading) => Padding(
ilk olarak fat arrow `()=>` yerine block body `(){}` kullanmamız indentation için ve okunabilirlik için daha iyi, tek satır olan yerlerde fat arrow kullanabilirsiniz.

@mirkancal arkadaşımızın da slack kanalında bahsettiği gibi, `Widget` döndüren fonksiyonlar oluşturmak flutter'da anti pattern, bunlar yerine  `StatelessWidget` yada `StatefulWidget` kullanırsak daha iyi olur.

2020-03-20 07:31 UTC, onatcipli commented on sozluk/lib/util/app_constant.dart
>    static final String svgLogo = "assets/tdk_logo.svg";
direk SVG olarak koymak yerine

https://fluttericon.com/
sitesinden font oluşturup kullanabiliriz. 

[mediumdaki yazıda](https://medium.com/flutterpub/how-to-use-custom-icons-in-flutter-834a079d977) biraz bahsetmiş nasıl yapabileceğimizden belki sonradan bu moda çevirebiliriz.

2020-03-20 07:31 UTC, onatcipli commented on sozluk/lib/page/home/home_page.dart
> +  Widget _itemTopMenu(String heading) => Padding(
mesela buradaki `Widget _itemTopMenu()` method'unu böyle bir `StatelessWidget`'a çevirebiliriz : 

```dart
class BuildItemTopMenu extends StatelessWidget {
  const BuildItemTopMenu({
    Key key,
    @required this.context,
  }) : super(key: key);

  final BuildContext context;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(top: 32.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          new RawMaterialButton(
            onPressed: () {
              Navigator.pop(context);
              _onDrawerButtonPressed();
            },
            child: new Icon(
              Icons.arrow_back_ios,
              color: AppConstant.colorBackButton,
              size: 13.0,
            ),
            shape: new CircleBorder(),
            elevation: 0,
            fillColor: AppConstant.colorDrawerButton,
            padding: const EdgeInsets.all(15.0),
          ),
          Spacer(),
          Text(
            heading,
            style: TextStyle(
              fontSize: 14,
              color: AppConstant.colorHeading,
              fontWeight: FontWeight.w500,
            ),
          ),
          Spacer(),
          Spacer(),
        ],
      ),
    );
  }
}
```

2020-03-20 07:38 UTC, mirkancal commented on sozluk/lib/util/app_constant.dart
>    static final String svgLogo = "assets/tdk_logo.svg";
Bu appin genelinde var, başka bir pr ile toplu düzelteceğim ben

2020-03-20 07:55 UTC, mirkancal approved these changes

2020-03-20 08:14 UTC, AliAnilKocak commented on sozluk/lib/page/home/home_page.dart
> +  Widget _itemTopMenu(String heading) => Padding(
Katılıyorum. Refactor edilmesi gerekli projenin. Belirli standartlar üzerinden yürümeliyiz. Oluşturulan herhangi bir widget için widgets klasörü içerisinde ayrı dosyalarda StatelessWidget ya da StatefulWidget ile tutmamız gerekir diye düşünüyorum. 

-search_box.dart
-idiom_card.dart gibi

Klasör düzeninin nasıl olması gerektiğini tartışabiliriz buradan. @onatcipli @Adem68 @mirkancal

2020-03-20 09:33 UTC, mirkancal commented on sozluk/lib/page/home/home_page.dart
> +  Widget _itemTopMenu(String heading) => Padding(
Sonrasında refactor ederiz, bu PR kodun şuandaki standardı için uygun

2020-03-20 09:33 UTC, merged

2020-03-23 02:11 UTC, mukireus commented on sozluk/lib/page/home/home_page.dart
> +  Widget _itemTopMenu(String heading) => Padding(
Stateless widget uygulamayı yormaz mı? Biraz daha detaylı açıklayabilir misiniz? Performans ve diğer önemlerini

2020-03-23 02:17 UTC, mukireus commented on sozluk/lib/page/home/home_page.dart
> +  Widget _itemTopMenu(String heading) => Padding(
En kısa zamanda refactor edeceğim. Bilgilendirmeler için teşekkür ederim